version: "3.7"
services:
  app_proxy:
    environnement:
      APP_HOST: netbootxyz
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"
  
  server:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.84 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - /path/to/config:/config # optional
      - /path/to/assets:/assets # optional
    ports:
      - 3000:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8090:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
